/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "HonoService": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "leadsDb": {
      "type": "sst.cloudflare.D1"
    }
  }
}
